CENTER_FREQ = 100e6

MIN_CENTER_FREQ_MHZ = 24

MAX_CENTER_FREQ_MHZ = 1766

SAMPLE_RATE = 2.048e6

NUM_SAMPLES = 8192

GAIN = 'auto'

WATERFALL_HISTORY = 200

FEATURE_MAX_AGE_SECONDS = 30.0

SIGNAL_HISTORY_MAX_AGE_SECONDS = 30.0

SIGNAL_CONTINUITY_GAP_SECONDS = 0.5

SIGNAL_PERSISTENCE_ACTIVE_SECONDS = 2.0

SIGNAL_PERSISTENCE_PERSISTENT_SECONDS = 5.0

SIGNAL_PERSISTENCE_LONG_SECONDS = 15.0

BANDWIDTH_STABILITY_MIN_SAMPLES = 3

FREQUENCY_STABILITY_MIN_SAMPLES = 3

FREQUENCY_STABILITY_REFERENCE_KHZ = 25.0

FEATURE_TRACKING_TOLERANCE_KHZ = 25.0

SIGNAL_DUTY_CYCLE_WINDOW_SECONDS = 10.0

SURVEY_MEASUREMENT_BUFFER_SIZE = 10

SURVEY_MIN_MEASUREMENT_FRAMES = 3
SURVEY_SETTLING_DELAY_MS = 500

PEAK_CONFIRMATION_REQUIRED_HITS = 2

PEAK_CONFIRMATION_WINDOW_FRAMES = 3

PEAK_CONFIRMATION_TOLERANCE_KHZ = 25.0

SMART_OCCUPANCY_MAX_SCORE = 50

SMART_POWER_MAX_SCORE = 30
SMART_POWER_SCORE_MIDPOINT = 15.0
SMART_POWER_SCORE_PER_DB = 0.3

SMART_PERSISTENCE_ACTIVE_SCORE = 5
SMART_PERSISTENCE_PERSISTENT_SCORE = 10
SMART_PERSISTENCE_LONG_SCORE = 15

SMART_AGE_5_SECONDS_SCORE = 3
SMART_AGE_15_SECONDS_SCORE = 6
SMART_AGE_30_SECONDS_SCORE = 10

SMART_STRENGTH_MEDIUM_SCORE = 3
SMART_STRENGTH_STRONG_SCORE = 6

SMART_MAX_SCORE = (
        SMART_OCCUPANCY_MAX_SCORE
        + SMART_POWER_MAX_SCORE
        + SMART_PERSISTENCE_LONG_SCORE
        + SMART_AGE_30_SECONDS_SCORE
        + SMART_STRENGTH_STRONG_SCORE
)
